### ISSUE TITLE
Instagram issue?

### ISSUE THREAD

**Issue by pantieninja** [BlackJack8/iOSAdblockList#10]
For starters, thank you for your work! I recently started using adblock for ios and came across your hosts file. Very impressive. So noob question- would it be normal for Instagram to have connection issues now that I have imported your DNS list? When I turn adblock off, Instagram works. When I turn it back on, it stops working. This has only been the case since I imported your list. I read in the readme that it's impossible to block instagram ads, so I find it weird that your list breaks my instagram. Any thoughts or help? Thanks in advance and keep up the excellent work!!

**Comment by pantieninja** [comment]
You know what, Instagram seems to be working again. It must have been something briefly on their end. Never mind! This can be closed. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BlackJack8** [comment]
Ok thank you!
