### ISSUE TITLE
false positive - www.alidns.com

### ISSUE THREAD

**Issue by MkQtS** [BlackJack8/iOSAdblockList#101]
`na61-na62.wagbridge.alibaba.tanx.com` is a CNAME of `www.alidns.com`. Adguard Home would block `www.alidns.com` as `na61-na62.wagbridge.alibaba.tanx.com` is included in the list.

Maybe `na61-na62.wagbridge.alibaba.tanx.com` should be removed, or just add `@@||www.alidns.com^` to avoid this.

**Comment by WhoCares1337** [comment]
www.adsbexchange.com does not exchange advertising. It distributes ADS-B data and should not be blocked.

**Comment by BlackJack8** [comment]
Will be fixed
