### ISSUE TITLE
assets-jpcust.jwpsrv.com videos-fms.jwpsrv.com

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#103]
These domains block embedded videos
Here is an example of the embedded video i could not play
https://forums.androidcentral.com/droid-bionic/130214-battery-symbol-question-mark-inside.html

**Comment by p1r473** [comment]
https://github.com/hemiipatu/PiHoleBlocklists/issues/8

**Comment by BlackJack8** [comment]
Will be fixed
