### ISSUE TITLE
False positive http://hgc-cf-cache-1.svonm.com/

### ISSUE THREAD

**Issue by thettenhausen** [BlackJack8/iOSAdblockList#104]
I am using a local app called moBiel which is used for buying tickets for our bus and tram service. They offer the option to buy discounted tickets if you "watch" an ad. These ads seem to be served from http://hgc-cf-cache-1.svonm.com/ - but they are requested by the user, not inserted as unwanted ads into other video streams or the like. 
Connection details from AdBlock app show source port 63216 and destination port is 53.
I guess this is an edge case as the domain also serves the "bad" kind of ads that is unwanted? Similar issue where the domain was blocked in uBO resulting in no videos being served on some websites was discussed here: https://github.com/uBlockOrigin/uAssets/issues/5120/

**Comment by BlackJack8** [comment]
Will be fixed
