### ISSUE TITLE
www.adsbexchange.com does not exchange advertising. It distributes ADS-B data and should not be blocked.

### ISSUE THREAD

**Issue by SkyDiscovery** [BlackJack8/iOSAdblockList#107]
www.adsbexchange.com does not exchange advertising. It distributes ADS-B data and should not be blocked.

_Originally posted by @WhoCares1337 in https://github.com/BlackJack8/iOSAdblockList/issues/101#issuecomment-937718217_

**Comment by SkyDiscovery** [comment]
Created PR #106 for it

**Comment by BlackJack8** [comment]
Will be fixed
