### ISSUE TITLE
False positive - www.roadandtrack.com

### ISSUE THREAD

**Issue by elmedico27** [BlackJack8/iOSAdblockList#108]
www.roadandtrack.com is a false positive included within the list.  Road & Track is an American automobile magazine from Hearst Publishing (see [Wikipedia](https://en.wikipedia.org/wiki/Road_%26_Track)).  While it does have at least one tracking subdomain, the _www_ root should not be blocked as an advertising domain.

**Comment by BlackJack8** [comment]
Will be fixed
