### ISSUE TITLE
Twitch ads are slipping through on iOS

### ISSUE THREAD

**Issue by akriosx** [BlackJack8/iOSAdblockList#13]
This happened with uBlock Origin a few days ago even on PC, will there be update to the hosts list that can get rid of them again?

**Comment by BlackJack8** [comment]
I don’t use twitch, so I added these domains which seem suspicious.

badges.twitch.tv
config.ioam.de
static-cdn.jtvnw.net

Doesn‘t look like it breaks anything. 
Feel free to tell me if that isn‘t the case!

**Comment by akriosx** [comment]
Hey Blackjack,

Just an update. This morning and briefly last night I have not seen anymore ads on both my PC and Twitch. And this was with me not updating the new entries you added. I'll keep you posted over the next few days! 

Thank you for the help

**Comment by akriosx** [comment]
Was fine again last night. However, browsing the uBlock origin and Twitch subreddits it appears Twitch has been pushing ads into streams differently the past week or so causing them to get by blockers. Seems to be a bit back and forth with the patches working and then not working.

**Comment by thuanma** [comment]
![34558408-8217-4BEA-9AE5-0BDB14424D1C](https://user-images.githubusercontent.com/49478576/55869488-ea5c9180-5bc9-11e9-96b6-6d1edcbef715.png)

New problem since yesterday, any ideas on how to fix that problem if this would help? Thanks for the advance.

**Comment by BlackJack8** [comment]
From where did you download this tweaked Instagram?

**Comment by thuanma** [comment]
It’s any kind of tweaked Instagram that was being downloaded, that ads some reason started to appeared more than 24 hours ago from now and it’s still appearing right now, it’s effecting Tweakbox app, Appvalley app, Tutu app, Panda Helper app and much more. This also includes InstaBlue app and InstaRed app as well. I’ll have all 3295 ad links blocked on my AdGuard pro blacklist and is currently fully on and active.

**Comment by BlackJack8** [comment]
It must be something on your end... i‘m using Adblock by Futuremind and don‘t see any ads in the apps mentioned above.

**Comment by thuanma** [comment]
Oh ok, so I’ve switched to Adblock by Futuremind and the UA ad banner still pop up as normal effecting any type of tweaked Instagram apps only, the rest of the other tweaked apps such as Facebook, YouTube and TikTok is looking good with no ads popping out.

So what I did is I’ve decided to recopy all the URL again and repaste it for both AdGuard and Adblock just Incase if there any new URL on your block list which was updated 18d ago and the UA ad banner still pops up on my birth iPhone 6s and iPad Air 2.

My latest screenshot from Instagram++ InstaRed and InstaBlue apps.

![A563550D-8AD5-4CF4-991C-BD39E3CDB416](https://user-images.githubusercontent.com/49478576/55941378-71227480-5c85-11e9-8f57-a68938ea58ba.png)
![66747B2F-1E1F-4E75-9E8F-D6682B7587BF](https://user-images.githubusercontent.com/49478576/55941379-71bb0b00-5c85-11e9-9a11-ee05f46b4e97.png)
![Uploading B71EBA3D-FB18-4C19-8EC5-37104CFFD5F8.png…]()

**Comment by BlackJack8** [comment]
Ok that is weird. Would you mind sending me screenshots of your dns proxy log? (On Adblock by futuremind)
Delete the log, and reopen the app where you see ads. Maybe your ads are country based and the domain is not on my list

**Comment by thuanma** [comment]
Oh ok I guess, I’m from Australia. Here the log of my dns proxy log on Adblock by futuremind after I’ve opening the app where I see ads (InstaBlue). Hopefully it will help.

![A9663602-E9DE-47C9-8B35-FA31727963A7](https://user-images.githubusercontent.com/49478576/55955642-48aa7280-5ca5-11e9-80da-bdecb10e1ea0.png)
![F5AC13EB-ACDB-4A22-B8EE-527C42C2B8E1](https://user-images.githubusercontent.com/49478576/55955643-48aa7280-5ca5-11e9-8cee-33f76ad51085.png)
![E006EF62-DBA8-44E0-BD91-39CBD1FBCC69](https://user-images.githubusercontent.com/49478576/55955644-49430900-5ca5-11e9-8b64-d3a61f0fd2a2.png)
![899ADB57-E726-443C-81B4-974A6A9F1C6D](https://user-images.githubusercontent.com/49478576/55955645-49430900-5ca5-11e9-80a8-08789649f8d0.png)

**Comment by BlackJack8** [comment]
Facebook ads... they are not blockable sadly. You‘d need a different dormat which isn‘t supported by Adblock and Adguard

**Comment by thuanma** [comment]
Oh ok thanks for that. So that ad is simular to the WhatsApp++ one that is not blockable right and here the the log of my dns proxy log on Adblock by futuremind.
![C1834254-961C-47E0-8B23-85F34E152092](https://user-images.githubusercontent.com/49478576/55956816-32ea7c80-5ca8-11e9-980a-ecec3178b60a.png)
![7F6F7A5A-9EE2-4B4C-93C1-285817EF8C5B](https://user-images.githubusercontent.com/49478576/55956817-33831300-5ca8-11e9-908e-b0732c5862e5.png)
![B65B1E13-6B37-40D0-AEC9-CE4A74B377F4](https://user-images.githubusercontent.com/49478576/55956820-341ba980-5ca8-11e9-8881-a41019fae276.png)

**Comment by thuanma** [comment]
Ok never mind, that banner UA ads still appear even if you don’t have the internet connected so there nothing anyone could do about it. I didn’t even know about it until what you said a few hours ago. Just change your system time from your device at least 10 days before today by going to setting > general > date and time. I did that just recently just now. It should work perfectly.

**Comment by thuanma** [comment]
Ok never mind, that banner UA ads still appear even if you don’t have the internet connected so there nothing anyone could do about it. I didn’t even know about it until what you said a few hours ago. Just change your system time from your device at least 10 days before today by going to setting > general > date and time. I did that just recently just now. It should work perfectly.

**Comment by thuanma** [comment]
Ok never mind, that banner UA ads still appear even if you don’t have the internet connected so there nothing anyone could do about it. I didn’t even know about it until what you said a few hours ago. Just change your system time from your device at least 10 days before today by going to setting > general > date and time. I did that just recently just now. It should work perfectly.
