### ISSUE TITLE
Duel Links Meta

### ISSUE THREAD

**Issue by ryanlikessquirrels** [BlackJack8/iOSAdblockList#16]
Hi, 

There’s a good site for a mobile game I play called Duel Links Meta. They have a pretty aggressive anti-Adblock system which sometimes gives me issues on desktop where I use uBlock Origin and Nanodefender. When I try to open this site in safari on my iPhone with the filter list it won’t load, the page is just all white. Any way you can check into this please?

Edit: site is www.duellinksmeta.com

**Comment by BlackJack8** [comment]
Weird. I'm having no issues with this site.

I recommend deleting all domains and groups you currently have and importing my list again. Maybe it's a domain included in Adblock.

If you didn't create a group for my domains, just delete the whole IP in Adblock.
Then add it again. 

iPv4 is 0.0.0.0
iPv6 is ::00

Hope that fixes it!
