### ISSUE TITLE
Buffer iOS app not working anymore 

### ISSUE THREAD

**Issue by Quorum75** [BlackJack8/iOSAdblockList#17]
Hello. 
Since the last update the Buffer iOS app (Buffer: Social Media Manager by Buffer, Inc.) is not working properly anymore. 
The fetching link function does work. 
Best. 
James

**Comment by BlackJack8** [comment]
I'm sorry but i can't reproduce the issue :(

May you send me some screenshots of the DNS Proxy Log under the settings in Adblock? 

Make sure to delete the current log. 
Leave Adblock open in the Background, open Buffer and reproduce the issue.
Go back to Adblock and make screenshots of the whole log.

I hope You can understand!

**Comment by Quorum75** [comment]
Sorry I finally found it. It was 0.0.0.0 bufferapp.com

**Comment by BlackJack8** [comment]
Weird... this domain is not on my list. 
Maybe it's included in the default lists, which i deleted because i have all necessary domains from them included.
