### ISSUE TITLE
Blocked domain breaks Twitch content: `static-cdn.jtvnw.net`

### ISSUE THREAD

**Issue by DRSDavidSoft** [BlackJack8/iOSAdblockList#22]
Hey again,

I just noticed that the **static-cdn.jtvnw.net** domain is serving legitimate content on the Twitch homepage, and as such should not be blocked.

This seems to be added about five months ago in 287645b and I believe it to be a false positive.

```
https://static-cdn.jtvnw.net/jtv_user_pictures/drsdavidsoft-profile_image-ed797ed14350f1c2-300x300.jpeg
```

Please notice the above example, which is my profile picture that is being served from the same domain.

**Comment by gio1991mm** [comment]
I can follow everyone on Twitch, but if I follow her and then go to someone else, I can no longer follow her. Everything is fine with her, but I don't know if everything is correct with me. Can you please check this? Thank you.

**Comment by gio1991mm** [comment]
<img width="2091" height="126" alt="Image" src="https://github.com/user-attachments/assets/225702ab-1f9d-4c54-bbe1-a03d2f4758d4" /> with others I can just follow and I keep following but with her for some reason I can't follow her and then I can and if I go to another channel on twich I don't follow the person again why is that, please explain that to me as well thank you

**Comment by gio1991mm** [comment]
Image with others I can just follow and I keep following but with her for some reason I can't follow her and then I can and if I go to another channel on twich I don't follow the person again why is that, please explain that to me as well thank you
she is not blocked I just can't follow her for some reason if I want to follow her 

<img width="224" height="224" alt="Image" src="https://github.com/user-attachments/assets/0d9934bd-0def-4403-a7b3-90448f90f49e" />I'll get that from her, I find it really strange, can you help me with that?

**Comment by gio1991mm** [comment]
I changed my profile picture and still can't follow her on Twitch

**Comment by DRSDavidSoft** [comment]
@gio1991mm This issue is unrelated to your problem.
