### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by DRSDavidSoft** [BlackJack8/iOSAdblockList#27]
Um, is there a reason that `www.aol.com` (AOL's main domain) is blocked?
https://github.com/BlackJack8/iOSAdblockList/blob/09b3650e58cff01d63bbc2ab8009fb36e1daa7e7/Hosts.txt#L3242

via df4a21ac0a016f430b86ae18d31209e6fbd49843

**Comment by BlackJack8** [comment]
Thank you, i removed it.
