### ISSUE TITLE
Unable to block ads in Instagram app?

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#28]
I just downloaded and imported https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/6f653df891c3dedd57b40473b4198f9b625b2f4c/Hosts.txt into my Adblock in my old iPhone 6+ (iOS v12.4.2). I tried Instagram app and still see its sponsored ads. Are they not blockable with DNSes or something? :(

**Comment by asaddon** [comment]
Yes, Instagram/Facebook Video/YouTube Video ads can not be blocked using simple DNS based blocking techniques because they serve the ads and actual content using the same domain and blocking that domain will block actual content as well.

**Comment by antdude** [comment]
Asaddon: Darn and thanks. Wow, even YouTube? :( I am so spoiled by using ad blockers in web browsers on my computers. I will go ahead and closer my issue. Keep up the good work though even though it can't block everything. :(
