### ISSUE TITLE
Question: Do I need to delete my old imported list before importing the new updated one?

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#29]
Or can I import to add? What about the changed and removed filters from the new list?

Thank you for reading and hopefully answering. :)

**Comment by BlackJack8** [comment]
Hey there!
I would delete the old list, as there will always be some false positives.
To make it easier to delete, create a new group before importing.

Please message me on Reddit next time if it's not an issue ;)

**Comment by antdude** [comment]
Thanks. We need an official forum or something!

**Comment by kaczma3** [comment]
>  false positives

hey Blackjack, may I ask what these false positives will do if you keep them? I always import the list even though it says I have duplicates. I'm wondering if this is hindering performance in any way.

**Comment by BlackJack8** [comment]
False positives are domains you don't want to be blocked. F.e. if i were to block Youtube.com and remove it later on, there might be a chance you still got youtube.com in your blocklist.

In conclusion i'd always delete the old domains before updating

**Comment by kaczma3** [comment]
> 
> 
> False positives are domains you don't want to be blocked. F.e. if i were to block Youtube.com and remove it later on, there might be a chance you still got youtube.com in your blocklist.
> 
> In conclusion i'd always delete the old domains before updating

How come you would block a domain only to unblock it later? Isn't it better to have a wide array of domains to block so that you prevent all sorts of ads to go through and whatnot?
