### ISSUE TITLE
potential additions

### ISSUE THREAD

**Issue by jawz101** [BlackJack8/iOSAdblockList#3]
I stumbled across your blocklist looking into the state of ad blocking on iOS.  I maintain a similar list for Android ads and, since most of these mobile monetization networks offer sdk's for both operating systems, there should be some overlap on what domains they use.  Anyways, I just wanted to pass along my list in case you want to take a look.  I'm looking over yours and see some of the same domains, so now I'm really just doing web searches to see what sort of companies they are.

https://github.com/jawz101/MobileAdTrackers

Question- were you really seeing hits by apps directly to www. pages?  I'm not too concerned with blocking their business website when I'm more concerned with the traffic to their ad subdomains.  I didn't know if the apps were necessarily throwing in ads pointing to their www. subdomain.

Also, fwiw, I run my list through a utility someone made called PyFunceble (a link to the utility is on that link above) that looks over hostfiles for dead hosts.  I ran yours through it and a bunch came back as no longer exists- like if a company goes out of business and stops paying for that domain.

I'll comment again with that list (it's still running)

**Comment by BlackJack8** [comment]
Hey there!
It really depends on the adblocker - Most automatically resolve www. 
Just like in the browser, the www. often just gets removed when opening the page.

I actually looked up if all domains still exist on my list, and they do somehow. If they are still being used, well, idk.
I‘m going to look it up with the tool you listed above.

Thanks for your help!

**Comment by BlackJack8** [comment]
If there are some issues with the www. at the beginning, i can of course remove that! I tried it with only one adblocker

**Comment by jawz101** [comment]
What ad blocker are you using?

Here's that list of potentially down sites.  
short version
[down-hosts.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542927/down-hosts.txt)

detailed version
[down_or_potentially_down.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542904/down_or_potentially_down.txt)

or split
[404.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542916/404.txt)
[409.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542917/409.txt)
[410.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542918/410.txt)
[400.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542919/400.txt)
[403.txt](https://github.com/BlackJack8/iOSAdblockList/files/2542920/403.txt)

how to read
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

From the wikipedia page, 400, 404 and 410 have a very strong indication of not existing while the others are possible.

If you have a whois or nslookup command on your computer you could try testing one of the others on the list versus one of the ones on these lists to see the difference.
`nslookup ads.ezboard.com` non existent example versus `nslookup google.com` one that is found.

NSlookup goes out to your DNS server & checks to see if it can resolve a domain name to IP address(es).

Then, another utility is called whois.  I usually go out to the web and find a site that has a web version of this tool.  What a whois does is tell you who owns the domain.  (also note some people buy one with anonymizer services to hide their details.  ICANN is a pretty official site.  another is maybe GoDaddy's since they sell domain names.  There are tons of sites that offer this utility as well as command-line utilities or bulk checking gui tools that can look them up too.

web examples:
https://whois.icann.org/en/lookup?name=google.com
https://www.godaddy.com/whois/results.aspx?domain=google.com

Sometimes I use these tools to see who might really own a domain just to see what sort of business they are.

**Comment by BlackJack8** [comment]
I‘m using Adblock by Futuremind

„Here's that list of potentially down sites.
short version
down-hosts.txt

detailed version
down_or_potentially_down.txt

or split
404.txt
409.txt
410.txt
400.txt
403.txt“

Quick question: Are these all from my list? It seems weird because some domains from there are not even in my list.

Thank you for the help!

**Comment by jawz101** [comment]
[cleanlist.txt](https://github.com/BlackJack8/iOSAdblockList/files/2543108/cleanlist.txt)

I kept working with it while I'm here and, ignoring the extra domains, this would be your list cleaned of dead hosts.  I sort by primary domain so I can see who owns clumps of domains.
ex: so like `s0.2mdn.net` and `2mdn.net` are clumped together instead of spread across the list.  If you've ever used Privacy Badger on Chrome or Firefox, they did this to their add-on after I started reorganizing their lists for readability :P

**Comment by BlackJack8** [comment]
I actually removed some domains since my last update, i would be pleased if you can do the same with the updated one when i get home in about 2-3 hours.

**Comment by jawz101** [comment]
Will do.  Yeah, that PyFunceble program is a little tricky to get set up.  The dev is trying to work through an easier install method at my request but- yeah- it's just a little tricky at least for me to get python figured out.

**Comment by jawz101** [comment]
Thanks.  I'll work on it in about an hour.

I was just thinking- how do you collect these domains?  Does your ad blocker log all DNS requests or something and you're picking out the unnecessary ones?  Is it traffic you see while just running various apps and games or also while you're browsing on your phone?  Is it just from use on the phone?

The reason I ask is I'm also considering just merging yours straight into mine since there's so much overlap between Android and iOS mobile ad companies so I might as well.

I'm also curious where in the world you live (like North America, Europe, Asia, etc.)  I'm in North America and the reason I ask is I'm curious if some of the different ad networks we're seeing might be due to the different sorts of regional markets we are in.  For instance, I'd rarely download a Chinese shopping app or something.  Just curious.

**Comment by BlackJack8** [comment]
Yes, my adblock logs all invoked domains.
If you want to merge it, feel free to. You helped me a lot!
I live in germany :)

**Comment by jawz101** [comment]
here's the output 
[output.zip](https://github.com/BlackJack8/iOSAdblockList/files/2544590/output.zip)

**Comment by jawz101** [comment]
Do you have an example of what I'd do to see any of those working successfully?  If that company decides to stop using it or something that would be a reason one gets caught as currently active.  Other than that, I'll have to ask the author of that tool what the reason might be if you see use of one still.

**Comment by jawz101** [comment]
Just by going here? https://www.teufel.de/datenschutz.html

I don't see that analytics.teufel.de in my dns logs nor in uBlock Origin when i visit that URL.


As for the akamai and cloudfront ones, perhaps they are addresses that are dynamically created.  Say, when you and only you visit that web page, it assigns you a unique identifier in the form of an actual subdomain.  Those content delivery networks, such as cloudfront, akamai, cloudflare, leaseweb, etc. do tricky things to work for many businesses who use their product.  One subdomain could represent a unique company or even uniquely identify you uniquely.

https://en.m.wikipedia.org/wiki/Content_delivery_network

**Comment by BlackJack8** [comment]
https://www.teufel.de/datenschutz-opt-out.html
It is adclear.teufel.de, not analytics.teufel.de

**Comment by jawz101** [comment]
ah... well, I don't know what to say for that.  Perhaps the PyFunceble author might be reached to see if something was wrong.  I'm going to close this for now though

**Comment by funilrys** [comment]
Hello there!

May I get your INVALID and INACTIVE files ? You may have discovered a critical issue.

Also are you using the stable or dev version ?

About adclear.teufel.de I'll look at it as it is really strange ....

Have a nice day/night.

Cheers,
Nissar

**Comment by BlackJack8** [comment]
This is the Output from jawz101:
https://github.com/BlackJack8/iOSAdblockList/files/2544590/output.zip

**Comment by jawz101** [comment]
@funilrys I was using the dev version - whatever the latest one was at that time I ran it.

**Comment by BlackJack8** [comment]
Wow, very weird what is happening there.
I‘ve just seen it in my dns proxy log, so i included it. 
That means this domain is obsolete, right?

Thank you for the help!

**Comment by funilrys** [comment]
Hi @BlackJack8, I can confirm it! I did run my tool over 5 countries in 3 different continents and I get the same result. Same with ping, nslookup and dig.

I also checked 1049.b.akamai.net, d3anogn3pbtk4v.cloudfront.net and your INACTIVE list, I also get the same.

May I invite you to read [this page](https://pyfunceble.readthedocs.io/en/dev/logic-representation.html#domain-testing) (for the dev version - which will be soon the stable version) and/or [this page](https://pyfunceble.readthedocs.io/en/latest/logic-representation.html) (for the current stable) ? 

It's just some simple flowcharts which may help you understand what we do behind PyFunceble.

If you have any questions or need help for something else, feel free to ping me!

Have a nice day/night.

Cheers,
Nissar

**Comment by BlackJack8** [comment]
Ok, thank you two for the help! I definetly learned something new :)
