### ISSUE TITLE
apple-finance.query.yahoo.com is blocked for iOS' Stocks app.

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#32]
As of yesterday, I noticed my iPhone 6+'s iOS v12.4.2's Stocks app couldn't get any updates and show datas because of blocked apple-finance.query.yahoo.com. I had to unblock to use Stocks app fully. I guess Apple recently changed its Stocks server provider?

**Comment by BlackJack8** [comment]
Didn't notice that.. will change it in the next update.
I have no idea if Apple changed their provider though.

**Comment by antdude** [comment]
Thank you for fixing that. Yeah, I didn't notice it until on Monday. I assume Apple changed it on their end. Didn't you have this blockage for a while too?

**Comment by BlackJack8** [comment]
Yeah the domain has been there for a long time actually, Stocks worked fine.

**Comment by antdude** [comment]
Ah. Then, it has to be Apple changing something on their end. Anyways, thanks again. It works nice now. :)
