### ISSUE TITLE
cdn.syndication.twimg.com Blocks inline tweets

### ISSUE THREAD

**Issue by ta6vie** [BlackJack8/iOSAdblockList#34]
Inline tweets in sites are blocked when above is enabled. Same with syndication.twimg.com

**Comment by BlackJack8** [comment]
Thank you! 
Fixed it.

**Comment by ta6vie** [comment]
syndication.twimg.com also blocks that & still there.

**Comment by BlackJack8** [comment]
Ok fixed it again
