### ISSUE TITLE
AdBlock 

### ISSUE THREAD

**Issue by tomtom53** [BlackJack8/iOSAdblockList#39]
Hello dear 
I like so much your hosting files but I have one question 
I use AdBlock on iOS and I want to know if it’s possible to remove / hides the cookies warnings ?
Thanks a lot

**Comment by yourduskquibbles** [comment]
You would need to use a filterlist (search for cookie on https://filterlists.com/) in combination with Adguard or other Safari content blocker

**Comment by BlackJack8** [comment]
Yes, it is. Go to Adblock > Settings > Manage Safari Rules > Add Subscription > and enter  https://www.i-dont-care-about-cookies.eu/abp/
along with https://www.fanboy.co.nz/fanboy-cookiemonster.txt

And you're done!

**Comment by tomtom53** [comment]
Thanks for this information indeed it works in safari but I use Firefox or google chrome most of time in my iPad so no solution I think ?

**Comment by BlackJack8** [comment]
I'm not sure whether Firefox and Chrome has content blocker support or not. If they don't, there is possibly no way to block them.
