### ISSUE TITLE
So many normal sites which are blocked

### ISSUE THREAD

**Issue by XxDarKxDukexX** [BlackJack8/iOSAdblockList#4]
Reddit, user.github etc are blocked please fix this

**Comment by BlackJack8** [comment]
Hi,
I‘m sorry to hear you have problems.
Unfortunately neither Reddit nor Github is being blocked for me.
I recommend you to do a clean installation of my list; First you remove all my domains from the list, then you install them again.
Many people are still using an older version of my list and getting problems.
I hope i could help you!

Best Regards,
BlackJack8

**Comment by XxDarKxDukexX** [comment]
Hi this is very odd as I subscribed to the hosts on AdGuard Pro on both my iPhone and iPad and I still get blocked from many websites and when I check the dns requests it says this hosts list blocked the website. I have already deleted the subscription and re added it many times but it still shows the same issues.

**Comment by XxDarKxDukexX** [comment]
Hi I think I have found the issue. I don’t think Aduard Pro supports this kind of format for hosts file so I’m pretty sure I have to do it manually cause when I tried it on AdBlock this worked. I’m pretty certain that this e.g. https://hosts-file.net/ad_servers.txt is the type of format they would like it in.

**Comment by XxDarKxDukexX** [comment]
If you could make it compatible with AdGuard Pro that would be very helpful thanks

**Comment by XxDarKxDukexX** [comment]
I was only using your list and I have issued this problem to AdGuard if they could add support to this format

**Comment by XxDarKxDukexX** [comment]
Sorry I can’t get the sites being blocked as there are too many sites which are randomly blocked

**Comment by Bincyx** [comment]
Open it in Notepad++
Find What:^
Replace With:0.0.0.0

**Comment by BlackJack8** [comment]
Ohhh didnt know Adguard Pro needed the iPv4 format.
Yeah so in order for my blocklist to work, you need 0.0.0.0 before every domain.

**Comment by BlackJack8** [comment]
Here you go: https://github.com/BlackJack8/iOSAdblockList/blob/master/iPv4Hosts.txt

**Comment by XxDarKxDukexX** [comment]
Hi thanks so much for doing this I’ll really appreciate if you update the iPv4 Hosts aswell thanks

**Comment by BlackJack8** [comment]
Of course i will. Does everything work fine now?

**Comment by XxDarKxDukexX** [comment]
Yup it works perfectly now with AdGuard Pro thanks for doing this
