### ISSUE TITLE
static.zdassets.com

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#40]
This domain broke the  help section of the Kobo/Rakuten website for me

![image](https://user-images.githubusercontent.com/9235633/77137732-70719100-6a45-11ea-9224-12f386b95ba1.png)

**Comment by BlackJack8** [comment]
Thanks for reporting, fixed it!

**Comment by p1r473** [comment]
Seems to be still blocked @BlackJack8

**Comment by BlackJack8** [comment]
All false positives will be removed in the next update. I'm currently not home, but expect an update soon.
