### ISSUE TITLE
Please remove pool.ntp.org

### ISSUE THREAD

**Issue by MaxMcBurn** [BlackJack8/iOSAdblockList#43]
Hi BlackJack8,

please remove "pool.ntp.org" from your list as it is for sync world time.
https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt

many thanx in advance and keep up the good work!! you made may day with this list :)

greetinx from germany

**Comment by BlackJack8** [comment]
Thank you, will be fixed on the next update. 
Btw, i'm also from germany ;)
