### ISSUE TITLE
unblock ipinfo.io

### ISSUE THREAD

**Issue by MaxMcBurn** [BlackJack8/iOSAdblockList#44]
Moin mein Held :-)

Bitte sei so gut und nehme auch ipinfo.io aus Deiner Liste .. das ist ein seriöser Dienst für Abfargen von IP-Adressen. Ich glaube, das kannst Du getrost entfernen.

Danke, gruß und bleib gesund!

**Comment by BlackJack8** [comment]
Schon gemacht :) Danke fürs Melden.
