### ISSUE TITLE
Excessive Battery drain On IOS 13.4

### ISSUE THREAD

**Issue by ta6vie** [BlackJack8/iOSAdblockList#45]
After updating to IOS 13.4 I have noticed that adblock consumes a lot of battery. It was not like this before. Is this due to host file size or app itself?

[https://i.imgur.com/nVXteML.png](url)

**Comment by BlackJack8** [comment]
This is weird.
What device do you have and at what is the battery health of it?
Adblock can be buggy sometimes. I'd recommend reinstalling Adblock to see if that helps.

**Comment by ta6vie** [comment]
iPhone X, battery life is 91. 

I haven’t removed it as I have manually added lists, concerned to loose them. 

//Hussain

**Comment by BlackJack8** [comment]
How many domains do you have active?
My list contains about 15.000 domains, which isn't much and should easily be handled by Adblock.

**Comment by ta6vie** [comment]
Only your domains plus around 100 manually added domains. I removed it and reinstalled again. Will see what happens. I was using it with your domains since long time and never encountered this drain before.

//Hussain

**Comment by BlackJack8** [comment]
Is it better now?
If not, you should maybe take a look at Adguard Pro. It is more lightweight and also has more functions than Adblock, like filter list subscription, custom DNS servers and a whitelist.

**Comment by kaczma3** [comment]
Big battery drain in the background with argued pro on iOS 13

**Comment by ta6vie** [comment]
Yeah looks better now. I’ll keep monitoring it otherwise I’ll consider switching to Adguard Pro ( I have bought it before). Your list could be also used in Adguard pro, correct?


//Hussain

**Comment by ta6vie** [comment]
> 
> 
> Big battery drain in the background with argued pro on iOS 13

looks like it is general not only Adblock. Could it be because of 13.4 specifically. I haven't had this on 13.3

**Comment by BlackJack8** [comment]
May be. I have an iPhone 11 Pro Max Jailbroken on 12.2.3 and there is no battery drain.

**Comment by kaczma3** [comment]
Yeah, since iOS 13 has always on for VPN it uses continuous battery in the background. It’s seriously having me reconsider Adblockers now because I’m constantly deciding between battery and ads. I usually choose the former now :/

**Comment by ta6vie** [comment]
Does any domain on the list block iCloud sync? It looks like the app is not able to sync to iCloud this is why it keep running in the background.

**Comment by BlackJack8** [comment]
Can you send me a screenshot of Adblocks' DNS Proxy log when this happens?

**Comment by ta6vie** [comment]
[https://imgur.com/a/RKm87zc](url)

iCloud sync will be always like in the photo stocked (it does not even start). But nothing seems to be blocked from the log. I tried to disable your entire list and still the same with iCloud sync.

Before you asked for the screenshot I completely disable iCloud sync for Adblock but still there was background activity, strange!

**Comment by BlackJack8** [comment]
Oh you're talking about Adblock's iCloud Sync.. it is a known bug, it sometimes literally stays there forever. It doesn't cause battery drain afaik.

**Comment by ta6vie** [comment]
Then what is causing the background activity of Adblock now? It wasn't like this on 13.3 before updating to 13.4. It could be IOS 13.4 itself. I think Adblock needs to be updated to resolve this otherwise it will be big issue. I have emailed the developer but not sure if he takes this seriously.

**Comment by kaczma3** [comment]
> Then what is causing the background activity of Adblock now? It wasn't like this on 13.3 before updating to 13.4. It could be IOS 13.4 itself. I think Adblock needs to be updated to resolve this otherwise it will be big issue. I have emailed the developer but not sure if he takes this seriously.

Not sure but I’ve seen all apps that have VPN connect on demand use background on top of regular use from day one on iOS 13, so I’m not sure how you didn’t have that.

**Comment by ta6vie** [comment]
> > Then what is causing the background activity of Adblock now? It wasn't like this on 13.3 before updating to 13.4. It could be IOS 13.4 itself. I think Adblock needs to be updated to resolve this otherwise it will be big issue. I have emailed the developer but not sure if he takes this seriously.
> 
> Not sure but I’ve seen all apps that have VPN connect on demand use background on top of regular use from day one on iOS 13, so I’m not sure how you didn’t have that.

Before there was also background activity but no much battery drain. It was in range of 2-3% Which it’s acceptable but now there is battery drain.

**Comment by kaczma3** [comment]
Over 24 hours?

**Comment by ta6vie** [comment]
Yes
