### ISSUE TITLE
cdn.jsdelivr.net

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#46]
This domain is breaking image hosting on several pages

![image](https://user-images.githubusercontent.com/9235633/78462712-b57eff80-76a2-11ea-95cb-88f2aa97844c.png)
![image](https://user-images.githubusercontent.com/9235633/78462718-c3348500-76a2-11ea-8d69-dac987dff78b.png)

**Comment by BlackJack8** [comment]
Thank you for submitting, will be fixed in 10 minutes
