### ISSUE TITLE
False positive rule

### ISSUE THREAD

**Issue by fsangel** [BlackJack8/iOSAdblockList#56]
Hello,

Please exclude the whole rule "yandex.ru" from the lists because it blocks the largest web search engine in Russia. 

Here is the pic https://imgur.com/a/NXBvAKh

upd. + "gstaticadssl.l.google.com" - is breaking some google fonts

**Comment by leeuwtjex** [comment]
That's really stupid to block. Better block mcDonalds, coca cola and google.....

**Comment by fsangel** [comment]
+ "vk.com" is blocked too. It's the largest Russian social network like Facebook.

**Comment by BlackJack8** [comment]
Sorry for the late answer. Both domains are now removed
