### ISSUE TITLE
false positives: factual,  quality alternative news sites are blocked by blacjkack8

### ISSUE THREAD

**Issue by rugabunda** [BlackJack8/iOSAdblockList#58]
This is a legit website, please unban this asap.

BlackJack8-iOSAdblockList-raw-master-Miscellaneous(iPv4).txt

**Comment by insuusvenerati** [comment]
https://mediabiasfactcheck.com/russia-insider/?amp Ok

**Comment by rugabunda** [comment]
Russia-Insider is one of the greatest sources for reputable and quality news on earth. These other anti-propaganda, anti fake news sites are also being censored by fake news, unblock these too

www.naturalnews.com
www.unz.com
www.presstv.ir
www.antiwar.com
thesaker.is
www.whatreallyhappened.com
southfront.org
www.veteranstoday.com
www.projectveritas.com
www.pravdareport.com
www.sana.sy
www.fort-russ.com

**Comment by rugabunda** [comment]
You advertise your lists for blocking ads, not factual news. if you want to block real news sites, please create a dedicated list, and don't mix in legitimate websites in your adblock list, all based on some corporate elitist media bias so called fact checker.

**Comment by BlackJack8** [comment]
I might as well just delete the miscellaneous list, as i have once took it over from a friend and am not willing to maintain it anymore. I will just keep my normal ad & tracker list. Thank you for your input.

**Comment by rugabunda** [comment]
Thanks! I took a quick look through that list and it includes a huge portion of all non corporate, alternative news media websites, I just removed that list, glad to see your other lists are clean.  Thanks for the update.
