### ISSUE TITLE
ghs.googlehosted.com

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#59]
Hi, 
This domain is Google Hosted content.
I ran into it as it was a CNAME for accessing humblebundle.com
I believe it is not malicious.

**Comment by BlackJack8** [comment]
Will be fixed in the next update. Thank you!

**Comment by p1r473** [comment]
When will next update be?
Thanks!

**Comment by BlackJack8** [comment]
> 
> 
> When will next update be?
> Thanks!

Just updated the list. I am very sorry for the delay, but i had to deal with a lot of emergency work.

**Comment by p1r473** [comment]
No problems at all! Thanks!
