### ISSUE TITLE
icanhazip.com should not be here

### ISSUE THREAD

**Issue by jabberwock** [BlackJack8/iOSAdblockList#68]
icanhazip.com keeps getting flagged by various security tools. ALL this site does is return the remote ip of the visitor via text/plain. It does not deliver anything else. It is very useful for people wondering their public IP. e.g. `curl icanhazip.com`

Can we please ensue this is not blacklisted?

**Comment by BlackJack8** [comment]
Hi, thank you for reporting. It will be fixed today.
