### ISSUE TITLE
Blocked domains breaks website functionality.

### ISSUE THREAD

**Issue by asaddon** [BlackJack8/iOSAdblockList#7]
These domain breaks the website einthusan.tv ( and probably others as well ) and they shouldn't be blocked IMO since they only hosts content and no ads related stuff.

**s3.amazonaws.com
d2wy8f7a9ursnm.cloudfront.net
d1azc1qln24ryf.cloudfront.net
fonts.gstatic.com
cdn.jsdelivr.net**

Also this domain breaks TikTok app playback:
**v16.muscdn.com**

**Comment by BlackJack8** [comment]
Ok so seems like the domains causing issues are vendorlist.consensu.org and cdn.jsdelivr.net
The other ones you listed are actually being used for tracking or ads.
I will remove these 2 domains and also v16.muscsn.com
Sorry for the issues
