### ISSUE TITLE
error block domain

### ISSUE THREAD

**Issue by qpzr** [BlackJack8/iOSAdblockList#70]
www.baidu.com 
www.wshifen.com
cdn.bootcss.com
anquan.org
pingjs.qq.com
l.qq.com
api.weibo.com
.......................

There are many unknown errors domain，I have no patience to find

IOSADblockList Where was it collected from ?
Why are there so many error doimain be block ?

IOSADblockList nice~!
but It's too difficult to use in China  
so I can only choose to give up

**Comment by BlackJack8** [comment]
I'm sorry for the inconvenience. I'm not very familiar with chinese websites, but i will unblock what you listed. Expect an update tomorrow

**Comment by BlackJack8** [comment]
Updated it just now, sorry for the delay. I´m working for health emergency, so my time is limited.
