### ISSUE TITLE
Dailymotion.com's iOS app and web site are blocked.

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#72]
https://imgur.com/a/FsyRC2D for screen shots from my old iPhone 6+ (iOS v12.4.7)'s Safari and Dailymotion app. Using AdGuard Pro v4.0.1. I had to allow it to make them work. :(

Thank you for reading and hopefully answering and fixing soon. :)

**Comment by BlackJack8** [comment]
Hmm, that's weird. There is no matching domain in my list, that would block dailymotion. I will be looking into it

**Comment by BlackJack8** [comment]
This issue has been fixed now. Please go ahead and refresh my filter in Adguard for the changes to take place. Thanks for letting me know!

**Comment by antdude** [comment]
Thanks. It worked. :)
