### ISSUE TITLE
NBA’s iOS app’s standings get blocked due to stats.nba.com.

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#74]
https://ibb.co/k6jMTRZ for my uploaded (screen shot/capture)s from my iPhone 6+ (iOS v12.4.8)’s Adguard Pro.

Thank you for reading and hopefully fixing soon.

**Comment by BlackJack8** [comment]
Thanks! I will fix that today.

**Comment by antdude** [comment]
You're welcome and thank you for fixing my reported issues quickly. ;)

**Comment by BlackJack8** [comment]
Ok, the update is live now.

**Comment by antdude** [comment]
It works. Thanks again. :)
