### ISSUE TITLE
ssl.google-analytics.com breaks one app I have. Is it ok to disable?

### ISSUE THREAD

**Issue by ta6vie** [BlackJack8/iOSAdblockList#77]

**Comment by BlackJack8** [comment]
Hey there! Which app does it break? Maybe we can sort it out.

**Comment by ta6vie** [comment]
It is a banking app called SAIB. It runs ok but when tried to log-in it gives error. When ssl.google-analytics.com is disabled it log-in without any error. This is the app link [https://apps.apple.com/us/app/saib/id596038022](url)

**Comment by BlackJack8** [comment]
After some research, i´d recommend to just whitlelist the domain. The thing is, ssl.google-analytics.com is used for other tracking purposes. I´ve not experienced any issues with it, so it´s definitely ok to be blocked.
