### ISSUE TITLE
remove from blocklist

### ISSUE THREAD

**Issue by jordanelliott23** [BlackJack8/iOSAdblockList#79]
i think firebasedynamiclinks-ipv4.googleapis.com is wrongfully blocked in host file. maybe im wrong but i dont think its a tracker

**Comment by jordanelliott23** [comment]
not so sure now that i read this: https://firebase.google.com/docs/dynamic-links

is it used for advertising or no?

**Comment by BlackJack8** [comment]
Hi! You are indeed right. I will remove this domain soon.
Thanks for reporting!
