### ISSUE TITLE
Unblock ocsp.comodoca.com and gtssl2-ocsp.geotrust.com

### ISSUE THREAD

**Issue by Zocker1999NET** [BlackJack8/iOSAdblockList#80]
Domain: `ocsp.comodoca.com`

Similar to #48, is primary used by browsers to detect via OCSP if a given certificate is not rejected yet.

**Comment by Zocker1999NET** [comment]
Appending following domains, seemed to be blocked by this blocklist, too:
- `gtssl2-ocsp.geotrust.com`

**Comment by BlackJack8** [comment]
Thank you for reporting. Seems like `gtssl2-ocsp.geotrust.com` used to be serving ads in Spotify, but after some research this is no longer true. I will remove both domains soon.

**Comment by BlackJack8** [comment]
Updated
