### ISSUE TITLE
bad filters

### ISSUE THREAD

**Issue by jordanelliott23** [BlackJack8/iOSAdblockList#84]
mwcm.nytimes.com
a.nytimes.com
samizdat-graphql.nytimes.com
als-svc.nytimes.com
a1.nyt.com
static.prd.map.nytimes.com
nyt5-assets.prd.map.nytimes.com
purr.nytimes.com
et.nytimes.com
agility.cnn.com
config.outturner.com (breaks cnn app)
lb.production-public.tubi.io (breaks tubi tv app)
m.ssl.fastly.net

**Comment by STLITGuy** [comment]
I agree. I tried to turn off some of the cnn filters but couldn’t figure out the one that’s blocking cnn from working.

**Comment by BlackJack8** [comment]
Hi, i'm very sorry for replying this late. I had some trouble accessing my Github account, but will be fixing the issue today.

**Comment by lkuner** [comment]
I'd also add
api.foursquare.com

It caused the Swarm to stop working and I don't think they run ads through its API.

**Comment by BlackJack8** [comment]
Alright, i´ve removed all the domains now. Thanks for reporting!
