### ISSUE TITLE
AdBlock Syntax Version.

### ISSUE THREAD

**Issue by DevShubam** [BlackJack8/iOSAdblockList#89]
AdGuard for iOS supports AdBlock Plus's Syntax.

So basically, it will block the domain entered, as well as subdomains of that domain so it will block more than just whats on the list.

Syntax can go as follows:

Say I am trying to block example.org

Normally I would just add example.org to the list, but let's say im trying to block everything to do with example.org

I can add the following rule:

||example.org^

I just think making one with adblocker syntax, will really improve this list.

**Comment by BlackJack8** [comment]
I'm already using this format in Hosts.txt

https://github.com/BlackJack8/iOSAdblockList/blob/master/Hosts.txt

**Comment by DevShubam** [comment]
Ah. Thank you!
