### ISSUE TITLE
404 error.

### ISSUE THREAD

**Issue by antdude** [BlackJack8/iOSAdblockList#90]
https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/iPv4Hosts.txt is gone!

**Comment by BlackJack8** [comment]
I´ve replaced it with [Regular Hosts.txt](https://github.com/BlackJack8/iOSAdblockList/blob/master/Regular%20Hosts.txt), since the 0.0.0.0 resolver is unused by all adblockers i know.

**Comment by BlackJack8** [comment]
In case you need 0.0.0.0 behind every domain, i will reinstate the list.

**Comment by antdude** [comment]
Ah. Your https://github.com/BlackJack8/iOSAdblockList web page still links to it in "... Use this link to subscribe to the list in Adguard Pro: https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/iPv4Hosts.txt"

**Comment by BlackJack8** [comment]
Will change that. Thank you for letting me know!
