### ISSUE TITLE
iOS Twitch app ads

### ISSUE THREAD

**Issue by akriosx** [BlackJack8/iOSAdblockList#92]
This list has done a great job blocking Twitch ads on iOS, unfortunately they'll been coming through past few weeks.

**Comment by BlackJack8** [comment]
Ads are often region based. Despite using a VPN in multiple countries, I could not find ads on Twitch. I will still try to fix this though.

**Comment by akriosx** [comment]
Yeah I've heard that before. The current solution for desktop is M3U8 proxies. I'm experiencing the ads in US. Thanks for taking a look.
