### ISSUE TITLE
False positive datawrapper.dwcdn.net

### ISSUE THREAD

**Issue by Rogacz** [BlackJack8/iOSAdblockList#93]
Hi
I have to white list domain datawrapper.dwcdn.net to be able to see graphs on news website
Example article (it may be behind paywall):
https://biqdata.wyborcza.pl/biqdata/7,159116,26991198,koronawirus-w-niedziele-18-kwietnia-xx-x-tys-osob-w-szpitalach.html
Link to single graph:
https://datawrapper.dwcdn.net/3ut8i/154/

**Comment by BlackJack8** [comment]
Thanks, I will fix that in the next update
