### ISSUE TITLE
[Remove Request] -  Blocking Amazon Cognito - cognito-identity.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#96]
cognito-identity.us-east-1.amazonaws.com is a false positive
Amazon Cognito is required for some AWS apps. 
For me, it is breaking SensorPush app. 
"Amazon Cognito helps you create unique identifiers for your end users that are kept consistent across devices and platforms. Amazon Cognito lets you add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily.

**Comment by BlackJack8** [comment]
Thank you, will be fixing it right after.
