### ISSUE TITLE
datawrapper.dwcdn.net

### ISSUE THREAD

**Issue by p1r473** [BlackJack8/iOSAdblockList#97]
Hi,
DataWrapper is just a data display CDN (content delivery network)
"Datawrapper: Create charts, maps, and tables https://www.datawrapper.de
Create interactive, responsive & beautiful data visualizations with the online tool Datawrapper — no code required"

By blocking the CDN, you are blocking any potential website that wants to use DataWrapper 

For example, the following site: https://projects.iq.harvard.edu/covid-cpi/home
![image](https://user-images.githubusercontent.com/9235633/128225274-7bb45626-d73f-421b-aed9-c7e2ca3460c9.png)

**Comment by BlackJack8** [comment]
Thank you for reporting, i will fix this right after.
